export default {
  DECK_OF_CARDS_API: "https://deckofcardsapi.com/api/deck/",
  MARBLE_COLORS: ["yellow", "green", "black", "white", "lightblue", "orange", "red", "blue"],
  NUM_POSITIONS_PER_TRACK: 18,
  CARDS: {
    EXIT_START: ["JACK", "QUEEN", "KING", "ACE"],
    MOVE_BACKWARD: ["8", "9", "10"],
    VALUES: {
      ACE: 1,
      JACK: 10,
      QUEEN: 10,
      KING: 10,
      2: 2,
      3: 3,
      4: 4,
      5: 5,
      6: 6,
      7: 7,
      8: 8,
      9: 9,
      10: 10,
    },
    SPLIT_MOVE: ["7", "9"],
  },
  PADDLE_ITEMS: [
    { class: "spacer-9" },
    {
      class: "position",
      dataAttributes: [{ attribute: "start", value: 1 }],
      position: "start-1",
      label: 1,
    },
    { class: "spacer-2" },
    {
      class: "position",
      dataAttributes: [{ attribute: "home", value: 1 }],
      position: "home-1",
      label: 1,
    },
    { class: "spacer-5" },
    { class: "spacer-8" },
    {
      class: "position",
      dataAttributes: [{ attribute: "start", value: 2 }],
      position: "start-2",
      label: 2,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "start", value: 3 }],
      position: "start-3",
      label: 3,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "start", value: 4 }],
      position: "start-4",
      label: 4,
    },
    { class: "spacer-1" },
    {
      class: "position",
      dataAttributes: [{ attribute: "home", value: 2 }],
      position: "home-2",
      label: 2,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "home", value: 3 }],
      position: "home-3",
      label: 3,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "home", value: 4 }],
      position: "home-4",
      label: 4,
    },

    { class: "spacer-3" },
    { class: "spacer-9" },
    {
      class: "position",
      dataAttributes: [{ attribute: "start", value: 5 }],
      position: "start-5",
      label: 5,
    },
    { class: "spacer-4" },
    {
      class: "position",
      dataAttributes: [{ attribute: "home", value: 5 }],
      position: "home-5",
      label: 5,
    },
    { class: "spacer-3" },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "18",
      label: 18,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "17",
      label: 17,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "16",
      label: 16,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "15",
      label: 15,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "14",
      label: 14,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "13",
      label: 13,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "12",
      label: 12,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "11",
      label: 11,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "10",
      label: 10,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }, { attribute: "exit" }],
      position: "9",
      label: 9,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "8",
      label: 8,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "7",
      label: 7,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "6",
      label: 6,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "5",
      label: 5,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }, { attribute: "door" }],
      position: "4",
      label: 4,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "3",
      label: 3,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "2",
      label: 2,
    },
    {
      class: "position",
      dataAttributes: [{ attribute: "track", value: null }],
      position: "1",
      label: 1,
    },
  ],
};
